title: 'Insight Minlaw'
description: Description
url: 'https://insight.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
future: true
paginate: 12
resources_name: articles
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
facebook-pixel: 255277428824423
favicon: /images/favicon-minlaw.ico
google_analytics: UA-10405444-22
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.d39jqws5vjjclc.amplifyapp.com/
prod: https://master.d39jqws5vjjclc.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: '#a40935'
  secondary-color: '#a40935'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
